<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Compile Remove="Behaviors\AuthorizationBehavior.cs" />
        <Compile Remove="Behaviors\TransactionBehavior.cs" />
    </ItemGroup>


    <ItemGroup>
        <ProjectReference Include="..\Domain\Domain.csproj" />
        <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
        <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

</Project>
