<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoWarn>NU1900</NoWarn>
        <!-- تنظیم مسیرهای خروجی -->
        <BaseOutputPath>$(MSBuildProjectDirectory)\bin</BaseOutputPath>
        <BaseIntermediateOutputPath>$(MSBuildProjectDirectory)\obj</BaseIntermediateOutputPath>
    </PropertyGroup>

    <!-- پکیج‌های مشترک بین همه پروژه‌ها (بدون ذکر نسخه) -->
    <ItemGroup>
        <PackageReference Include="MediatR" />
    </ItemGroup>

    <!-- پکیج‌های لایه WebApi -->
    <ItemGroup Condition="'$(MSBuildProjectName)' == 'WebApi'">
        <PackageReference Include="Asp.Versioning.Mvc" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Scalar.AspNetCore" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <!-- پکیج‌های لایه Infrastructure -->
    <ItemGroup Condition="'$(MSBuildProjectName)' == 'Infrastructure'">
        <PackageReference Include="Dapper" />
        <PackageReference Include="MimeKit" />
        <PackageReference Include="MailKit" />
        <PackageReference Include="Scalar.AspNetCore" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
        <PackageReference Include="Asp.Versioning.Mvc"  />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
        <PackageReference Include="RabbitMQ.Client" />
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.Sinks.File" />
        <PackageReference Include="Serilog.Sinks.Console" />
        <PackageReference Include="Serilog.Extensions.Logging" />
        <PackageReference Include="Serilog.Sinks.Seq" />
        <PackageReference Include="Microsoft.Extensions.Http" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
        <PackageReference Include="Polly" />
        <PackageReference Include="MongoDB.Driver" />
        <PackageReference Include="MongoDB.Bson" />
    </ItemGroup>

    <!-- پکیج‌های لایه Application -->
    <ItemGroup Condition="'$(MSBuildProjectName)' == 'Application'">
        <PackageReference Include="AutoMapper" />
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
        <PackageReference Include="Serilog.AspNetCore" />
    </ItemGroup>

    <!-- پکیج‌های لایه Domain -->
    <ItemGroup Condition="'$(MSBuildProjectName)' == 'Domain'">
        <PackageReference Include="Microsoft.Extensions.Identity.Stores" />
        <PackageReference Include="RabbitMQ.Client" />
        <PackageReference Include="MongoDB.Bson" />
    </ItemGroup>

    <!-- پکیج‌های لایه Shared -->
    <ItemGroup Condition="'$(MSBuildProjectName)' == 'Shared'">

    </ItemGroup>
</Project>